# Contributing in Quirks 🔍<!-- omit in toc -->

First of all, thanks for investing your time in contributing this project! :partying_face: :hugs:

The following guide will help you in workflow for Contributing to Quirks, as opening an issue or creating a PR. Feel free to propose changes to this document in a pull request. To get an overview of the project, read the [README](README.md).

## I have a question. How can I ask? :thinking_face:

> **Note:** Please don't create an issue to simply ask a question. You'll get faster results by using our channels like:

- [Official nabla Discord server](https://discord.gg/WzXYRd3AwH) (**recommended**) :gear:
- [nabla Official Twitter account](https://twitter.com/nabla_hq) :bulb:

## How Can I Contribute? :handshake:

### Reporting Bugs :bug:

This section guides you through submitting a bug report for Quirks. Following these guidelines helps maintainers and the community understand your report :pencil:, reproduce the behavior :computer:, and find related reports (when exists) :mag_right:.

#### Before Submitting A Bug Report :ballot_box_with_check:

- **Check if you can reproduce** the problem in the **latest version** of Quirks.
- **Perform a [cursory search](https://github.com/search?q=is%3Aissue+repo%3Anabla-studio%quirks)** to see if the problem has already been reported. If it has **and the issue is still open**, add a comment to the existing issue instead of opening a new one.

> **Note:** If you find a **Closed** issue which seems to describe your issue, open a new one and reference the original issue in the body of your new one.

#### How to submit a Bug Report? :incoming_envelope:

Bugs are tracked as [GitHub issues](https://guides.github.com/features/issues/). Create an issue on this repository and provide the needed information by filling in [the template](https://github.com/nabla-studio/quirks/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5BBug%5D%3A+).

You have to completely explain the problem and include additional details to help maintainers reproduce the problem:

- **Choose a clear and descriptive title** for the issue to identify the related problem.
- **Describe the exact steps to reproduce the problem** in as many details as possible. For example, start by explaining what action you produced. When listing steps, don't just say what you did, but explain **how** you did it. For example, if you reached a page, explain if you reached from direct link, or tapping some buttons.
- **Describe the behavior you observed after following the steps** and point out what exactly is the problem with that behavior.
- **Explain which behavior you expected to see instead and why.**
- **Include screenshots and animated GIFs** which show you following the described steps and clearly demonstrate the problem.
- **Include your public addresses**, if available
- **If the problem wasn't triggered by a specific action**, describe what you were doing before the problem happened and share more information using the guidelines below.

Provide more context by answering:

- **Is it possible to reliably reproduce this issue?** If not, please try to provide details about how often the problem happens and under which conditions it normally happens.
### Suggesting Enhancements :sparkles:

This section guides you through submitting an enhancement suggestion for Quirks, including completely new features and minor improvements to existing functionality. Following these guidelines helps maintainers and the community understand your suggestion :pencil: and find related suggestions :mag_right:.

#### Before Submitting An Enhancement Suggestion :ballot_box_with_check:

- **Perform a [cursory search](https://github.com/search?q=is%3Aissue+repo%3Anabla-studio%2Fquirks)** to see if the enhancement has already been suggested. If it has, add a comment to the existing issue instead of opening a new one.

#### How to submit a Enhancement Suggestion? :incoming_envelope:

Enhancement suggestions are tracked as [GitHub issues](https://guides.github.com/features/issues/). Create an issue on this repository and provide the needed information by filling in [the template](https://github.com/nabla-studio/quirks/issues/new?assignees=&labels=enhancement%2Cimprovement&template=enhancement-report.yml&title=%5BEnhancement%5D%3A+).

You have to explain the suggestion you want to propose and include additional details to help maintainers understand the suggestion:

- **Use a clear and descriptive title** for the issue to identify the suggestion.
- **Describe the current behavior** and **explain which behavior you expected to see instead** and why, by explaining as many steps as you can to correctly understand the whole story.
- **Include screenshots and animated GIFs** which help you demonstrate the steps or point out the part of Quirks which the suggestion is related to.
- **Explain why this enhancement would be useful** to most Quirks users.
- **List, if there exist, some other Mobile Wallet or similar services where this enhancement exists.**

### How to provide solutions :construction::heavy_plus_sign:

We love pull requests. Please follow these steps to have your contribution considered by the maintainers:

#### Getting Started :beginner:

1. Make sure you have a [**GitHub account**](https://github.com/signup/free>).
2. If you want to help in fixing a bug or to propose a solution for an improvement, firstly **check if there exists a related issue**. Otherwise **create a new one following the above documentation**.
3. **Fork the repository** on GitHub.
4. **Create a branch** for your edits starting by the `main` one.

#### Commit your update :new:

Commit the changes once you are happy with them. We use conventional commits on our repo, so please, **follow that convention**.

Once your changes are ready, don't forget to self-review to speed up the review process :zap:.

#### Pull Request :twisted_rightwards_arrows:

When you're finished with the changes, create a pull request, also known as a PR.

1. **Fill the "Pull Request" template** to help the reviewers understanding your changes as well as the purpose of your pull request.
2. Don't forget to [**link PR to issue**](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
3. **Enable the checkbox** to [allow maintainer edits](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so the branch can be updated for a merge.

Once you submit your PR, a team member will review your proposal. We may ask questions or request for additional information.

- We may ask for changes to be made before a PR can be merged, either using [suggested changes](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request) or pull request comments. You can apply suggested changes directly through the UI. You can make any other changes in your fork, then commit them to your branch.
- As you update your PR and apply changes, mark each conversation as [resolved](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#resolving-conversations).

#### Thank you! :pray:

Congratulations, your work is now available to the whole nabla community. :tada::clap:

The nabla team thanks you :sparkles:.

We also thanks to Github and Faker.py team for their contributing guides.