name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  git_bot_token:
    description: Git Bot token used to push to protected branches because github token can't
    required: false
  node_version:
    description: Node.js version
    required: false
    default: '20.12.0'
  bun_version:
    description: bun version
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.git_bot_token || github.token }}
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

    - name: Setup git user to "🤖 nabla Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "🤖 nabla Bot"

    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: ${{ runner.OS }}-20.x-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-20.x-

    - name: bun i
      shell: bash
      run: bun i --frozen-lockfile
