name: Release

description: Release packages

inputs:
  github_token:
    description: GitHub token
    required: true
  npm_token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - name: Version
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      # Use bunx instead of yarn because yarn automagically sets NPM_* environment variables
      # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
      # which is set up by `setup-node` action.
      shell: bash
      run: bunx nx affected -t version --parallel=1
