/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cosmos Wallet.json is a metadata file that contains information about a wallet of a specific platform and which chains it supports, either natively or via custom client-side addition.
 */
export interface CosmosWallet {
  $schema: string;
  wallet_name: string;
  pretty_name: string;
  website?: string;
  git_repo?: string;
  supported_chains: string[];
  connection_type?: 'browser_extension' | 'wallet_connect';
  features?: ('suggest_chain' | 'get_supported_chains' | 'icns')[];
  platforms: {
    device: 'mobile' | 'tablet' | 'desktop' | 'other';
    type: 'application' | 'extension';
    platform:
      | 'chrome'
      | 'edge'
      | 'opera'
      | 'brave'
      | 'firefox'
      | 'ios'
      | 'android'
      | 'otherOS'
      | 'otherBrowser';
    install_link?: string;
  }[];
  images: {
    png?: string;
    svg?: string;
    theme?: {
      primary_color_hex?: string;
      circle?: boolean;
      dark_mode?: boolean;
    };
    /**
     * logomark == icon only; logotype == text only; logo == icon + text.
     */
    layout: 'logo' | 'logomark' | 'logotype';
    /**
     * Indicates in which position the text is placed, in case the layout is 'icon' type, it's required only in this case.
     */
    text_position?: 'top' | 'bottom' | 'left' | 'right' | 'integrated';
  }[];
  wallet_connect?: {
    /**
     * define all the properties related to deeplink functionality.
     */
    deeplink?: {
      /**
       * it is the path of the deelink URL that will trigger wallet connect actions within a mobile wallet.
       */
      path?: {
        ios?: string;
        android?: string;
        universal?: string;
      };
    };
  };
  mobile?: {
    android?: {
      /**
       * The package name for your Android standalone app. You make it up, but it needs to be unique on the Play Store. See this [StackOverflow question](https://stackoverflow.com/questions/6273892/android-package-name-convention).
       */
      package_name?: string;
      /**
       * Custom schema that provide a way to reference resources inside an app, documented [here](https://developer.android.com/training/app-links/deep-linking).
       */
      schema?: string;
      /**
       * Universal schema for universal deeplink that provide a way to reference resources inside an app, documented [here](https://developer.android.com/training/app-links).
       */
      universal_schema?: string;
    };
    ios?: {
      /**
       * The bundle identifier for your iOS standalone app. You make it up, but it needs to be unique on the App Store. See this [StackOverflow question](https://stackoverflow.com/questions/11347470/what-does-bundle-identifier-mean-in-an-ios-project).
       */
      bundle_identifier?: string;
      /**
       * Custom URL schemes provide a way to reference resources inside an app, documented [here](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app).
       */
      schema?: string;
      /**
       * Universal schema for universal deeplink that provide a way to reference resources inside an app, documented [here](https://developer.apple.com/ios/universal-links/).
       */
      universal_schema?: string;
    };
  };
}
