import type { CosmosWallet } from '../types';

export const cosmostationmobile: CosmosWallet = {
  $schema: '../../wallet.schema.json',
  wallet_name: 'cosmostation',
  pretty_name: 'Cosmostation',
  website: 'https://www.cosmostation.io/',
  git_repo: 'https://github.com/cosmostation/cosmostation-android',
  supported_chains: [
    'cosmoshub',
    'akash',
    'assetmantle',
    'axelar',
    'bandchain',
    'bitcanna',
    'bitsong',
    'cerberus',
    'chihuahua',
    'canto',
    'comdex',
    'coreum',
    'crescent',
    'cryptoorgchain',
    'cudos',
    'desmos',
    'emoney',
    'evmos',
    'fetchhub',
    'gravitybridge',
    'injective',
    'irisnet',
    'impacthub',
    'juno',
    'kava',
    'kichain',
    'konstellation',
    'kujira',
    'kyve',
    'likecoin',
    'lumnetwork',
    'neutron',
    'noble',
    'nyx',
    'omniflixhub',
    'onomy',
    'osmosis',
    'panacea',
    'passage',
    'persistence',
    'provenance',
    'quasar',
    'regen',
    'rizon',
    'secretnetwork',
    'sentinel',
    'shentu',
    'sifchain',
    'sommelier',
    'stargaze',
    'starname',
    'stride',
    'teritori',
    'umee',
  ],
  platforms: [
    {
      device: 'mobile',
      type: 'application',
      platform: 'ios',
      install_link: 'https://apps.apple.com/kr/app/cosmostation/id1459830339',
    },
    {
      device: 'mobile',
      type: 'application',
      platform: 'android',
      install_link:
        'https://play.google.com/store/apps/details?id=wannabit.io.cosmostaion',
    },
  ],
  images: [
    {
      png: 'https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/cosmostationmobile/images/logo.png',
      svg: 'https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/cosmostationmobile/images/logo.svg',
      theme: {
        primary_color_hex: '#9C6CFF',
        circle: false,
        dark_mode: false,
      },
      layout: 'logomark',
    },
  ],
  mobile: {
    ios: {
      bundle_identifier: 'io.wannabit.cosmostation',
    },
    android: {
      package_name: 'wannabit.io.cosmostaion',
    },
  },
};
