import type { CosmosWallet } from '../types';

export const cosmostationextension: CosmosWallet = {
  $schema: '../../wallet.schema.json',
  wallet_name: 'cosmostationextention',
  pretty_name: 'Cosmostation',
  connection_type: 'browser_extension',
  website: 'https://www.cosmostation.io/',
  git_repo: 'https://github.com/cosmostation/cosmostation-chrome-extension',
  supported_chains: [
    'cosmoshub',
    'akash',
    'assetmantle',
    'axelar',
    'bandchain',
    'bitcanna',
    'bitsong',
    'canto',
    'cerberus',
    'chihuahua',
    'comdex',
    'coreum',
    'crescent',
    'cryptoorgchain',
    'cudos',
    'desmos',
    'emoney',
    'evmos',
    'fetchhub',
    'gravitybridge',
    'injective',
    'irisnet',
    'impacthub',
    'juno',
    'kava',
    'kichain',
    'konstellation',
    'kujira',
    'kyve',
    'likecoin',
    'lumnetwork',
    'neutron',
    'noble',
    'nyx',
    'omniflixhub',
    'onomy',
    'osmosis',
    'panacea',
    'passage',
    'persistence',
    'provenance',
    'quasar',
    'regen',
    'rizon',
    'secretnetwork',
    'sentinel',
    'shentu',
    'sifchain',
    'sommelier',
    'stafihub',
    'stargaze',
    'starname',
    'stride',
    'teritori',
    'tgrade',
    'umee',
  ],
  features: ['suggest_chain', 'icns'],
  platforms: [
    {
      device: 'desktop',
      type: 'extension',
      platform: 'chrome',
      install_link:
        'https://chrome.google.com/webstore/detail/cosmostation/fpkhgmpbidmiogeglndfbkegfdlnajnf?utm_source=chrome-ntp-icon',
    },
  ],
  images: [
    {
      png: 'https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/cosmostationextension/images/logo.png',
      svg: 'https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/cosmostationextension/images/logo.svg',
      theme: {
        primary_color_hex: '#9C6CFF',
        circle: false,
        dark_mode: false,
      },
      layout: 'logomark',
    },
  ],
};
