import { cookies } from 'next/headers';
import { Provider } from '../components/provider';

export const metadata = {
  title: 'Welcome to nextjs',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookie = cookies().get('quirks');

  return (
    <html lang="en">
      <body>
        <Provider cookie={cookie?.value}>{children}</Provider>
      </body>
    </html>
  );
}
